---

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  tags:
    - apt
    - update_cache

- name: Install virtualenvwrapper package dependencies
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  register: install_virtualenvwrapper_package_dependencies
  when: virtualenvwrapper_package_dependencies is defined
  with_items: virtualenvwrapper_package_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_virtualenvwrapper_package_dependencies.stdout_lines

- name: Install virtualenvwrapper dependencies
  sudo: yes
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_virtualenvwrapper_dependencies
  when: virtualenvwrapper_dependencies is defined
  with_items: virtualenvwrapper_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_virtualenvwrapper_dependencies.stdout_lines